name: Integration Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: 1.10.29
  RUST_TOOLCHAIN: stable

jobs:
  changes:
    runs-on: buildjet-8vcpu-ubuntu-2004
    # Set job outputs to values from filter step
    outputs:
      package: ${{ steps.filter.outputs.package }}
      workflow: ${{ steps.filter.outputs.workflow }}
    steps:
    - uses: actions/checkout@v3
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          package:
            - 'program/**'
          workflow:
            - '.github/workflows/integration-test.yml'
  build-and-integration-test:
    runs-on: buildjet-8vcpu-ubuntu-2004
    env:
      cache_id: program-candy-guard 
    needs: changes
    if: ${{ needs.changes.outputs.package == 'true' || needs.changes.outputs.workflow == 'true' }}
    steps:
      # Setup Deps
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-linux-build-deps
      - uses: ./.github/actions/install-solana
        with: 
          solana_version: ${{ env.SOLANA_VERSION }}
      - uses: ./.github/actions/install-rust
        with: 
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      # Restore Cache from previous build/test
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./rust/target
          key: ${{ env.cache_id }}-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ env.RUSTC_HASH }}

      # Build Rust Program
      - uses: ./.github/actions/build

      # Install JS SDK deps
      - uses: ./.github/actions/yarn-install-and-build
        with: 
          cache_id: sdk-candy-guard
          working_dir: ./js

      # Start local validator
      - name: start-local-test-validator
        working-directory: ./js
        run: DEBUG=amman* yarn amman:start
      
      # Run integration test
      - name: integration-test-candy-guard-program
        id: run_integration_test
        working-directory: ./js
        run: DEBUG=mpl* yarn test

      # Stop local validator
      - name: stop-local-test-validator
        working-directory: ./js
        run: yarn amman:stop
